# Generated by Django 4.2.21 on 2025-05-13 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('img_banner', models.ImageField(blank=True, upload_to='gamesplash/content_images/banner/')),
                ('img_poster', models.ImageField(blank=True, upload_to='gamesplash/content_images/poster/')),
                ('img_detail_poster', models.ImageField(blank=True, upload_to='gamesplash/content_images/poster/')),
                ('img_detail_banner', models.ImageField(blank=True, upload_to='gamesplash/content_images/banner/')),
                ('img_trailer', models.ImageField(blank=True, upload_to='gamesplash/content_images/trailer/')),
                ('img_thumbnail', models.ImageField(blank=True, upload_to='gamesplash/content_images/thumbnai/')),
                ('game_url', models.CharField(max_length=2000)),
                ('timedelta', models.DurationField(blank=True, null=True)),
                ('play_times', models.IntegerField(default=1)),
                ('upload_date', models.DateField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PlayedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='played_game', to='content.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_content', to='ums.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.gamecategory'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.gamegenre'),
        ),
        migrations.AddField(
            model_name='game',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.vendorprofile'),
        ),
    ]
